### PR TITLE
enable AppVeyor

### PR DESCRIPTION
**Pull request by tkelman**
Anyone willing to have this running on their appveyor account? I have a few too many packages running on mine and would like to avoid making their queue time any worse if possible.

### CODE REVIEW

**Comment by yuyichao** [comment]
Done (hopefully....)

**Comment by yuyichao** [comment]
https://ci.appveyor.com/project/yuyichao/gzip-jl

**Comment by yuyichao** [comment]
Do I need to manually add the webhook?

**Comment by tkelman** [comment]
Thanks! I can turn it on if you go to the settings on appveyor and send me the webhook url

**Comment by tkelman** [comment]
Hm. [`ccall` into `dup`](https://github.com/JuliaLang/GZip.jl/blob/c9422def3f2a7b866a4b8d611ca3a4dddcc73aac/src/GZip.jl#L278) isn't very portable, and neither is [shelling out to `which`](https://github.com/JuliaLang/GZip.jl/blob/c9422def3f2a7b866a4b8d611ca3a4dddcc73aac/test/runtests.jl#L22). Forgot about #41, maybe we should clean that up.

**Comment by tkelman** [comment]
may as well at least have the right config file...

**Pull request merged**
