### PR TITLE
Update GZip.jl

### PR DESCRIPTION
**Pull request by sbromberger**
Remove deprecation warnings in latest 0.4

### CODE REVIEW

**Comment by simonster** [comment]
Probably needs JuliaLang/Compat.jl#107 not to break 0.3

**Comment by sbromberger** [comment]
of course. One sec.

**Comment by sbromberger** [comment]
Not sure why that test is failing.

**Comment by tkelman** [comment]
because https://github.com/JuliaLang/Compat.jl/issues/107 has not been fixed or tagged yet

**Comment by alyst** [comment]
I have no idea why, but with these deprecation warnings the GC state was not turning back on for me. Could it be because of ```depwarn()```? So +1 to merging this PR ASAP.
Also, should the GC state be saved and restored to the original one instead of "true"?

**Comment by simonster** [comment]
I just tagged a Compat.jl release that implements JuliaLang/Compat.jl#107. But there's no need to use the `@compat` macro here.

**Comment by kmsquire** [comment]
I restarted the build (which should pass), but as @simonster pointed out, you should remove `@compat`, as nothing needs to be rewritten.

**Comment by garborg** [comment]
@sbromberger Looks good. Squash the commits?

**Comment by sbromberger** [comment]
Not easily, I don't think - I edited within github.

**Comment by garborg** [comment]
Okay, I pushed your first commit to master b998284b9627361cab8c3a22e00191d19a1c09d1

**Comment by sbromberger** [comment]
Thanks. Sorry - I've been out all day.

**Comment by garborg** [comment]
No problem. Thanks for tracking down and fixing the issue.

**Comment by sbromberger** [comment]
My pleasure. Would you mind tagging so I can update my REQUIRE? Thanks!

**Comment by garborg** [comment]
Pending in JuliaLang/METADATA.jl#2824

**Comment by sbromberger** [comment]
Awesome! Thanks again.

**Pull request closed without merging**
